### ISSUE TITLE
search block is not accessible from mobile version

### ISSUE THREAD

**Issue by czhci** [NeuBIAS/bise#54] opened 2019-01-31 16:25 UTC

**Comment by miura** [comment] 2019-01-31 17:38
This is a duplicate of #47 
search block will become available when the drop-down menu ("hamburger") becomes unlocked.

**Comment by miura** [comment] 2019-02-03 16:10
Production site is fixed. 

![685659b7-3615-43ac-85ce-20e033428345](https://user-images.githubusercontent.com/272781/52179070-fbf27900-27d5-11e9-98e7-84fe362703ec.png)

This actually is a kind of bug, that the first sidebar seems to be taken out in mobile-mode as the setting in themes/contrib/zircon/css/responsive.css is like that. 

![4289ae7c-4256-4bb2-814c-559d9729d7e0](https://user-images.githubusercontent.com/272781/52179083-247a7300-27d6-11e9-9980-c55b8f6a02e1.png)

As this file is managed by composer and not tracked by Github,  next time when zircon is updated, line 177 should be commented out and line 178 should be inserted.

**Comment by miura** [comment] 2019-02-03 16:11
... and I also found that this is nothing to do with the mobile menu icon not responding..

**Closed by miura** 2019-02-03 16:11 UTC
Labels: bug

**Comment by miura** [comment] 2019-02-03 16:37
https://www.drupal.org/project/zircon/issues/2704809
