### ISSUE TITLE
Add node ID ("nid") or `URL into biii` as output of http://biii.eu/searchjsonexport

### ISSUE THREAD

**Issue by joakimlindblad** [NEUBIAS/bise#115] opened 2019-10-16 14:18 UTC
For JSON export to COMULIS we need to link back to biii. 
Current json returned by e.g. 
[http://biii.eu/searchjsonexport?search_api_fulltext=(?=visualization)&_format=json&source=COMULIS
](http://biii.eu/searchjsonexport?search_api_fulltext=(?=visualization)&_format=json&source=COMULIS
)
does not include that required info (either Node ID or direct link).

Possibly requiring edit of file: [https://github.com/NeuBIAS/bise/blob/dev/config/sync/views.view.testsearch.yml](https://github.com/NeuBIAS/bise/blob/dev/config/sync/views.view.testsearch.yml) which seems to expose `searchjsonexport`

Note: This export is also used by ImageJ search plugin, so verify that functionality when making changes.

**Comment by PerrineGilloteaux** [comment] 2019-10-16 17:25
Done in test.biii.eu. @joakimlindblad Close when pushed to production

**Comment by joakimlindblad** [comment] 2019-10-24 22:17
The "empty fields" issue seems solved. 
Now, just to get the "nid" field back (first in test.biii, and then to migrate to the real one) :-)

**Comment by miura** [comment] 2019-10-24 22:58
are you going to work on this? @joakimlindblad

**Comment by joakimlindblad** [comment] 2019-10-25 00:52
I have a hope that @PerrineGilloteaux will fix it (as I wrote on Glip).

**Comment by PerrineGilloteaux** [comment] 2019-11-20 15:30
Adeed in the ugly way on test.biii.eu (could not launch my local instance to commit the change). Basically, add ID content data source in SERACH REST EXPORT view as field to be displayed

**Comment by joakimlindblad** [comment] 2020-03-01 10:42
@PerrineGilloteaux Any chance to progress this during Bordeaux Taggathon?

**Comment by PerrineGilloteaux** [comment] 2020-03-02 11:36
duplicate of #139

**Comment by joakimlindblad** [comment] 2020-03-02 11:46
This is independent of #139 
Currently it is just to propagate test.biii.eu behaviour to main biii.eu

**Comment by PerrineGilloteaux** [comment] 2020-07-08 15:35
nid is actually provided in searchjson export for now . 
Example of output from http://biii.eu/searchjsonexport?search_api_fulltext=(?=visualization)&_format=json
[{"title":"Openimadis","search_api_relevance":"12","body":"\u003Cp\u003EOpenImadis stands for Open Image Discovery: A platform for Image Life Cycle Management. It was previously called CID iManage (for Curie Image Database).\u003C\/p\u003E\n\n\u003Cp\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cstrong\u003ENo image data conversions, no duplication.\u003C\/strong\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/p\u003E\n\n\u003Cp\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E- \u003C\/span\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003E\u003Cspan\u003EUploads data to a secure server in the original format\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/span\u003E\u003C\/p\u003E","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2018-08\/openImadis.png?itok=uNfJSTtB","nid":"1341"},{"title":"Imaris","search_api_relevance":"6.801","body":"\u003Cp\u003EImaris is a software for data visualization, analysis, segmentation and interpretation of 3D and 4D microscopy images. It performs interactive volume rendering that lets users freely navigate even very large datasets (hundreds of GB). It performs both manual and automated detection and tracking of biological \u0093objects\u0094 such as cells, nuclei, vesicles, neurons, and many more. ImarisSpots for example is a tool to detect \u0093spherical objects\u0094 and track them in time series. Besides the automated detection it gives the user the ability to manually delete and place new spots in 3D space.","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2019-10\/descarga.png?itok=ctaIXQcb","nid":"87"},{"title":"MorphoNet","search_api_relevance":"6","body":"\u003Cp\u003EMorphoNet is a novel concept of web-based morphodynamic browser to visualise and interact with complex datasets, with applications in research and teaching.\u00a0\u003C\/p\u003E\n\n\u003Cp\u003EMorphoNet offers a comprehensive palette of interactions to explore the structure, dynamics and variability of biological shapes and its connection to genetic expressions.\u00a0\u003C\/p\u003E","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2020-03\/screenschot_0.png?itok=9okOp_ob","nid":"1626"},{"title":"Volocity Visualization","search_api_relevance":"6","body":"\u003Cp\u003EVolocity Visualization is designed to provide rapid, interactive, high resolution volume rendering of multi-channel 3D and 4D data sets. This Volocity product puts you in control of the way that you view your 3D data, offering a choice of rendering methods so that you can achieve the best results.\u00a0 A range of file formats can be imported from\u00a0 wide field and confocal microscopes, and snapshots and movies can be created quickly and easily to share and publish.\u003C\/p\u003E","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2019-10\/d23d23.PNG?itok=hQdkEmFx","nid":"595"},{"title":"Paintera","search_api_relevance":"5.961","body":"\u003Cp\u003EPaintera is a general visualization tool for 3D volumetric data and proof-reading in segmentation\/reconstruction with a primary focus on neuron reconstruction from\u00a0\u003Ca href=\u0022http:\/\/www.rsc.org\/publishing\/journals\/prospect\/ontology.asp?id=CMO:0001800\u0026amp;MSID=B310802C\u0022\u003Eelectron micrographs\u003C\/a\u003E\u00a0in\u00a0\u003Ca href=\u0022https:\/\/en.wikipedia.org\/wiki\/Connectomics\u0022\u003Econnectomics\u003C\/a\u003E. It features\/supports:\u003C\/p\u003E","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2018-12\/paintera-example-with-synapses.png?itok=aIqqWd8a","nid":"1392"},{"title":"","search_api_relevance":"5","body":"","field_image":"","nid":""},{"title":"Vaa3D","search_api_relevance":"4.817","body":"\u003Cp\u003EVaa3D is a handy, fast, and versatile 3D\/4D\/5D Image Visualization and Analysis System for Bioimages and Surface Objects. It also provides many unique functions that you may not find in other software. It is Open Source, and supports a very simple and powerful plugin interface and thus can be extended and enhanced easily.\u003C\/p\u003E","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2017-09\/Vaa3D.jpg?itok=odmdNhSX","nid":"62"},{"title":"","search_api_relevance":"4","body":"","field_image":"","nid":""},{"title":"Trainable Weka Segmentation","search_api_relevance":"3.985","body":"\u003Cp\u003EQuote:\u003C\/p\u003E\n\n\u003Cblockquote\u003E\n  \u003Cp\u003EThe Trainable Weka Segmentation is a Fiji plugin that combines a collection of machine learning algorithms with a set of selected image features to produce pixel-based segmentations. Weka (Waikato Environment for Knowledge Analysis) can itself be called from the plugin. It contains a collection of visualization tools and algorithms for data analysis and predictive modeling, together with graphical user interfaces for easy access to this functionality. As described on their wikipedia site, the advantages of Weka include:\u003C\/p\u003E","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2018-05\/TrainableWekaSegmentation-GUI-after-training.png?itok=RK5PFuIR","nid":"324"},{"title":"arivis Vision4D","search_api_relevance":"3.92","body":"\u003Cp\u003Earivis Vision4D is a modular software for working with multi-channel 2D, 3D and 4D images of almost unlimited size independent of available RAM. Many imaging systems, such as high speed confocal, Light Sheet\/ SPIM and 2 Photon systems, can produce a huge amount of multi-channel data, which arivis Vision4D handles without constraints.","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/default_images\/NEUBIASlogo.png?itok=pvuUqhrP","nid":"151"}]

Corrected not directly related by commit 0c310c640ccd187b85a7c7d774069276a79c5361 to remove maybe unclear html tag : 
[{"title":"Openimadis","search_api_relevance":"12","body":"OpenImadis stands for Open Image Discovery: A platform for Image Life Cycle Management. It was previously called CID iManage (for Curie Image Database).\n\nNo image data conversions, no duplication.\n\n- Uploads data to a secure server in the original format","nid":"1341","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2018-08\/openImadis.png?itok=uNfJSTtB"},{"title":"Imaris","search_api_relevance":"6.801","body":"Imaris is a software for data visualization, analysis, segmentation and interpretation of 3D and 4D microscopy images. It performs interactive volume rendering that lets users freely navigate even very large datasets (hundreds of GB). It performs both manual and automated detection and tracking of biological \u0093objects\u0094 such as cells, nuclei, vesicles, neurons, and many more. ImarisSpots for example is a tool to detect \u0093spherical objects\u0094 and track them in time series. Besides the automated detection it gives the user the ability to manually delete and place new spots in 3D space.","nid":"87","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2019-10\/descarga.png?itok=ctaIXQcb"},{"title":"MorphoNet","search_api_relevance":"6","body":"MorphoNet is a novel concept of web-based morphodynamic browser to visualise and interact with complex datasets, with applications in research and teaching.\u00a0\n\nMorphoNet offers a comprehensive palette of interactions to explore the structure, dynamics and variability of biological shapes and its connection to genetic expressions.\u00a0","nid":"1626","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2020-03\/screenschot_0.png?itok=9okOp_ob"},{"title":"Volocity Visualization","search_api_relevance":"6","body":"Volocity Visualization is designed to provide rapid, interactive, high resolution volume rendering of multi-channel 3D and 4D data sets. This Volocity product puts you in control of the way that you view your 3D data, offering a choice of rendering methods so that you can achieve the best results.\u00a0 A range of file formats can be imported from\u00a0 wide field and confocal microscopes, and snapshots and movies can be created quickly and easily to share and publish.","nid":"595","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2019-10\/d23d23.PNG?itok=hQdkEmFx"},{"title":"Paintera","search_api_relevance":"5.961","body":"Paintera is a general visualization tool for 3D volumetric data and proof-reading in segmentation\/reconstruction with a primary focus on neuron reconstruction from\u00a0electron micrographs\u00a0in\u00a0connectomics. It features\/supports:","nid":"1392","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2018-12\/paintera-example-with-synapses.png?itok=aIqqWd8a"},{"title":"","search_api_relevance":"5","body":"","nid":"","field_image":""},{"title":"Vaa3D","search_api_relevance":"4.817","body":"Vaa3D is a handy, fast, and versatile 3D\/4D\/5D Image Visualization and Analysis System for Bioimages and Surface Objects. It also provides many unique functions that you may not find in other software. It is Open Source, and supports a very simple and powerful plugin interface and thus can be extended and enhanced easily.","nid":"62","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2017-09\/Vaa3D.jpg?itok=odmdNhSX"},{"title":"","search_api_relevance":"4","body":"","nid":"","field_image":""},{"title":"Trainable Weka Segmentation","search_api_relevance":"3.985","body":"Quote:\n\n\n  The Trainable Weka Segmentation is a Fiji plugin that combines a collection of machine learning algorithms with a set of selected image features to produce pixel-based segmentations. Weka (Waikato Environment for Knowledge Analysis) can itself be called from the plugin. It contains a collection of visualization tools and algorithms for data analysis and predictive modeling, together with graphical user interfaces for easy access to this functionality. As described on their wikipedia site, the advantages of Weka include:","nid":"324","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/2018-05\/TrainableWekaSegmentation-GUI-after-training.png?itok=RK5PFuIR"},{"title":"arivis Vision4D","search_api_relevance":"3.92","body":"arivis Vision4D is a modular software for working with multi-channel 2D, 3D and 4D images of almost unlimited size independent of available RAM. Many imaging systems, such as high speed confocal, Light Sheet\/ SPIM and 2 Photon systems, can produce a huge amount of multi-channel data, which arivis Vision4D handles without constraints.","nid":"151","field_image":"\/sites\/default\/files\/styles\/thumbnail\/public\/default_images\/NEUBIASlogo.png?itok=pvuUqhrP"}]

**Closed** 2020-07-08 15:35 UTC
Labels: Waiting for deployment
