### ISSUE TITLE
Synonyms are not taken into account in the full-text search (BUG)

### ISSUE THREAD

**Issue by matuskalas** [NEUBIAS/bise#111] opened 2019-10-16 08:26 UTC

**Comment by joakimlindblad** [comment] 2020-03-03 13:52
This is almost as important as #137

**Comment by PerrineGilloteaux** [comment] 2023-05-15 12:11
closed as duplicate of https://github.com/NEUBIAS/bise/issues/202

**Closed by PerrineGilloteaux** 2023-05-15 12:11 UTC
Labels: bug, search-related
