### ISSUE TITLE
duplicated display of the same entry several times

### ISSUE THREAD

**Issue by czhci** [NEUBIAS/bise#52] opened 2019-01-31 15:59 UTC
when did this "overlay" advanced search (http://test.biii.eu/all-content?field_type_target_id=All&field_has_function_target_id=4097&field_has_topic_target_id_1=All&field_has_interaction_level_target_id=All&field_license_openness_target_id=All&field_has_programming_language_target_id=All&title_1=), it returned three items of MaMuT, when clicking in, they all point to the same page. why showing three times?

**Comment by czhci** [comment] 2019-01-31 15:59
another example is in Taggers panel.

**Comment by PerrineGilloteaux** [comment] 2019-02-02 11:17
Note that this is not happening in my working directory of local branch taggathonLuxembourg , which at commit 20e85098bbbd4b4f629a3ffdcc4204bc1fe0ac87 is a clone of neubias/bise dev and master (apart settings.php, I had some database access problem): there is no duplicate and it is going far more faster , even with the exact same database. @miura did you do the config import as well while deploying? ANy other difference that you could have in mind? It is hard to fix Because it is not reproducible locally.

**Comment by PerrineGilloteaux** [comment] 2019-02-02 11:48
Additional info: I ve cleared my browser cache and the Biii.eu cache as well. Still no difference. Once difference that I can see is that the database update has apparently not be done on biii.eu. Did you run updatedb on the main server @miura ?

**Comment by PerrineGilloteaux** [comment] 2019-02-03 10:34
Working on production site biii http://biii.eu/all-content?field_type_target_id=All&field_has_function_target_id=4097&field_has_topic_target_id_1=All&field_has_interaction_level_target_id=All&field_license_openness_target_id=All&field_has_programming_language_target_id=All&title_1= 
(@kota the test site is ahead of dev, so I did not touch, could you checked?) The Duplivcate output was solved by updating the configuration Following commit 8d73ab86b5a9623264173b61b8ff6a98daa4c776

**Comment by PerrineGilloteaux** [comment] 2019-10-16 13:08
The same problem is happening in new page. What was the fix?

**Comment by miura** [comment] 2020-06-19 01:11
This is fixed in test.biii.eu by now. 
http://test.biii.eu/all-content?type=All&field_has_function_target_id%5B%5D=4097&field_type_target_id=All

![image-20200619031023509](https://user-images.githubusercontent.com/272781/85086293-790b6c00-b1da-11ea-9dfe-1413ffd5ce7d.png)

**Closed by miura** 2020-06-19 01:11 UTC
Labels: bug, help wanted
