### ISSUE TITLE
Full-text search needs to be tuned (AS BAD AS BUG)

### ISSUE THREAD

**Issue by matuskalas** [NEUBIAS/bise#112] opened 2019-10-16 08:39 UTC
**A more specific search should return fewer results than a more generic search.**
(CC @joakimlindblad)

This is also how Google search works:
- https://www.google.com/search?q=elastic+registration finds 24M hits
- https://www.google.com/search?q=elastic finds 316M hits

This is the opposite and wrong in BIII search:
- https://biii.eu/search?search_api_fulltext=elastic+registration returns 39 hits
- https://biii.eu/search?search_api_fulltext=elastic returns 5 hits

**Comment by PerrineGilloteaux** [comment] 2023-05-15 12:27
closed as duplicate of https://github.com/NEUBIAS/bise/issues/193

**Closed by PerrineGilloteaux** 2023-05-15 12:27 UTC
Labels: enhancement, search-related, website dev
