### ISSUE TITLE
Link plugin with the collection the belong too. 

### ISSUE THREAD

**Issue by Lplantard** [NEUBIAS/bise#121] opened 2019-10-17 15:21 UTC
Some plugins belong to a collection. It would be nice from the collection entry to have links going to the individual plugins.

**Comment by miura** [comment] 2019-10-24 00:11
This probably will be solved by #94

**Comment by PerrineGilloteaux** [comment] 2023-05-15 12:16
closed as duplicate of https://github.com/NEUBIAS/bise/issues/94

**Closed by PerrineGilloteaux** 2023-05-15 12:16 UTC
Labels: duplicate, enhancement
